[[libcap]]
arch = "aarch64"
git-tree-sha1 = "4e3269a009eeeb35bbf2840727fc8fe5f794c9f2"
libc = "glibc"
os = "linux"

    [[libcap.download]]
    sha256 = "32c437c01f4e0985340903ab492806a3f3a877a646694a98627d1d8a19fb2959"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.aarch64-linux-gnu.tar.gz"
[[libcap]]
arch = "aarch64"
git-tree-sha1 = "d9aaf8bd7d12e05689b5fffbc653770ae68701f9"
libc = "musl"
os = "linux"

    [[libcap.download]]
    sha256 = "dc03237bbd0730abf9bd60315aeb2bc4fb186a903768fe35f6de3e2c44285589"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.aarch64-linux-musl.tar.gz"
[[libcap]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89c65f6e1e7077658c0c3baea9429a8ca7b1acad"
libc = "glibc"
os = "linux"

    [[libcap.download]]
    sha256 = "02ab078420aa25274680f004d03231847d45481ebeb060d7e1d7a2e98c258fae"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.armv6l-linux-gnueabihf.tar.gz"
[[libcap]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a7c87ac10100e52061d530b7625624987c4bae2b"
libc = "musl"
os = "linux"

    [[libcap.download]]
    sha256 = "4c26412b2da1bc8a74e0bb5f38e008cd5e893bac61d2f4ced5bdd11323553742"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.armv6l-linux-musleabihf.tar.gz"
[[libcap]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0fa48a1fdae3b9084178dedf91a3163cabd79d0"
libc = "glibc"
os = "linux"

    [[libcap.download]]
    sha256 = "ea0e6e602f56a67b46c97cca2bd3a02781ea39566961bbb627d4ba30c27a0d2e"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.armv7l-linux-gnueabihf.tar.gz"
[[libcap]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da4864933c50dfdf3c7fdd2ce6991057e7499675"
libc = "musl"
os = "linux"

    [[libcap.download]]
    sha256 = "c9bb54635bfc93670530b72927e15fa9eafd2704b138bc27ef074b22e24e0f34"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.armv7l-linux-musleabihf.tar.gz"
[[libcap]]
arch = "i686"
git-tree-sha1 = "e1ab837783c9b6c64696e3f78eddc426b1c6068b"
libc = "glibc"
os = "linux"

    [[libcap.download]]
    sha256 = "95ad12911d86ba4a58efacbc48ef96c83aa0125701d56060078fc5f15e227a1a"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.i686-linux-gnu.tar.gz"
[[libcap]]
arch = "i686"
git-tree-sha1 = "358de42b2c9c3d39aa8c00e44b6c29b25dc842b3"
libc = "musl"
os = "linux"

    [[libcap.download]]
    sha256 = "168f5376c68e7953fc6c60eb460e9200f947cbc24b4f235c4ee05eafb6b25a3d"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.i686-linux-musl.tar.gz"
[[libcap]]
arch = "powerpc64le"
git-tree-sha1 = "e13478163e302ebea949b11be333e3cfb0b65a18"
libc = "glibc"
os = "linux"

    [[libcap.download]]
    sha256 = "1c35fad87d3143c9762c9b48c9450e3d7821f579dee8589888af37badf600922"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.powerpc64le-linux-gnu.tar.gz"
[[libcap]]
arch = "x86_64"
git-tree-sha1 = "a6dcc5a48768a380e7243c7ef0ebcf64c69f4c2d"
libc = "glibc"
os = "linux"

    [[libcap.download]]
    sha256 = "b35b908cc30a2a65699e164c5f0a871a304335281c8225db6153cf129521bac2"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.x86_64-linux-gnu.tar.gz"
[[libcap]]
arch = "x86_64"
git-tree-sha1 = "e21ae33cd4327b8e5f7a8e12ccaf52b3e96b765d"
libc = "musl"
os = "linux"

    [[libcap.download]]
    sha256 = "295cc20d0f4c353ed25cb673aee7ac2d56368bab7f73e3fe7443d7f5626a6ef8"
    url = "https://github.com/JuliaBinaryWrappers/libcap_jll.jl/releases/download/libcap-v2.70.0+0/libcap.v2.70.0.x86_64-linux-musl.tar.gz"
