# Autogenerated wrapper script for libcap_jll for armv6l-linux-gnueabihf
export capability_h, libcap

JLLWrappers.@generate_wrapper_header("libcap")
JLLWrappers.@declare_file_product(capability_h)
JLLWrappers.@declare_library_product(libcap, "libcap.so.2")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        capability_h,
        "include/sys/capability.h",
    )

    JLLWrappers.@init_library_product(
        libcap,
        "lib/libcap.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
